/**
 * Generates (and verifies) the golden pricing vectors that lock the Java
 * backend to the TypeScript calculator.
 *
 * The expected values are COMPUTED from src/lib/pricing.ts — the same module the
 * public calculator imports — so they can never be a hand-typed guess that
 * happens to agree with nobody.
 *
 *   node --experimental-strip-types scripts/pricing-vectors.ts --write
 *   node --experimental-strip-types scripts/pricing-vectors.ts --check
 *
 * Or via npm: `npm run pricing:gen` / `npm run pricing:verify`.
 *
 * The Java side reads the same file in PricingCalculatorTest. If either
 * implementation drifts, one of the two checks goes red.
 */
import { writeFileSync, readFileSync, existsSync, mkdirSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import {
  MAX_ITEMS,
  MOTOR_SURCHARGE,
  ROLLER_RATE,
  ZEBRA_RATE,
  calculateLinePrice,
  type PricingInput,
} from "../src/lib/pricing.ts"

const here = dirname(fileURLToPath(import.meta.url))

const VECTORS_SUFFIX = "shademaster-admin-backend/src/test/resources/pricing-vectors.json"

/**
 * Where the backend's test resources live.
 *
 * The Java project can reasonably sit either inside this repo or beside it, so
 * rather than hardcoding one guess we try both and use whichever exists. An
 * explicit `--out=<path>` always wins, which is what CI should pass.
 */
const CANDIDATES = [
  resolve(here, "..", VECTORS_SUFFIX), // backend inside the web app
  resolve(here, "../..", VECTORS_SUFFIX), // backend as a sibling of the web app
]

function resolveOut(): string {
  const explicit = process.argv.find((a) => a.startsWith("--out="))?.slice(6)
  if (explicit) return resolve(explicit)

  const existingFile = CANDIDATES.find((p) => existsSync(p))
  if (existingFile) return existingFile

  // Nothing written yet — fall back to the first candidate whose backend
  // directory actually exists, so `--write` lands somewhere sensible.
  const existingDir = CANDIDATES.find((p) => existsSync(dirname(p)))
  return existingDir ?? CANDIDATES[0]
}

type Case = PricingInput & { note: string }

/**
 * Cases chosen to pin down the parts most likely to diverge in a port:
 * the ceil() on a fraction, exact multiples of 12, the roller/zebra branch,
 * the surcharge being applied per shade (before quantity), and quantity > 1.
 */
const CASES: Case[] = [
  { note: "placeholder sizes from the form, roller, manual", width: 78, height: 57, productType: "roller", motorized: false, quantity: 1 },
  { note: "same window, zebra rate", width: 78, height: 57, productType: "zebra", motorized: false, quantity: 1 },
  { note: "surcharge applies per shade", width: 78, height: 57, productType: "roller", motorized: true, quantity: 1 },
  { note: "zebra + surcharge", width: 78, height: 57, productType: "zebra", motorized: true, quantity: 1 },
  { note: "exact multiples of 12 must NOT round up", width: 72, height: 48, productType: "roller", motorized: false, quantity: 2 },
  { note: "surcharge multiplies with quantity", width: 72, height: 48, productType: "zebra", motorized: true, quantity: 3 },
  { note: "fractional width still ceils to the same foot", width: 78.1, height: 57, productType: "roller", motorized: false, quantity: 1 },
  { note: "a hair over a foot rounds up a whole foot", width: 12.5, height: 12, productType: "roller", motorized: false, quantity: 1 },
  { note: "large motorized order", width: 100, height: 80, productType: "roller", motorized: true, quantity: 3 },
  { note: "sub-inch dimensions still bill one square foot", width: 0.5, height: 0.5, productType: "roller", motorized: true, quantity: 1 },
  { note: "minimum realistic window", width: 1, height: 1, productType: "roller", motorized: false, quantity: 1 },
  { note: "exactly one square foot, zebra", width: 12, height: 12, productType: "zebra", motorized: false, quantity: 1 },
  { note: "bulk motorized zebra", width: 36, height: 36, productType: "zebra", motorized: true, quantity: 10 },
  { note: "large opening, no surcharge", width: 144, height: 120, productType: "roller", motorized: false, quantity: 1 },
  { note: "tall narrow window, multiple units", width: 60, height: 96, productType: "zebra", motorized: false, quantity: 4 },
]

function build() {
  return {
    $comment:
      "GENERATED by scripts/pricing-vectors.ts from src/lib/pricing.ts. Do not hand-edit. " +
      "Consumed by the Next.js parity check and by the Spring Boot PricingCalculatorTest.",
    constants: {
      rollerRate: ROLLER_RATE,
      zebraRate: ZEBRA_RATE,
      motorSurcharge: MOTOR_SURCHARGE,
      maxItemsPublicCalculator: MAX_ITEMS,
      currency: "CAD",
    },
    cases: CASES.map((c) => ({
      note: c.note,
      width: c.width,
      height: c.height,
      productType: c.productType,
      motorized: c.motorized,
      quantity: c.quantity,
      expected: calculateLinePrice(c),
    })),
  }
}

const outPath = resolveOut()
const mode = process.argv.includes("--write") ? "write" : "check"
const payload = JSON.stringify(build(), null, 2) + "\n"

if (mode === "write") {
  mkdirSync(dirname(outPath), { recursive: true })
  writeFileSync(outPath, payload)
  console.log(`wrote ${build().cases.length} vectors -> ${outPath}`)
} else {
  if (!existsSync(outPath)) {
    console.error(`pricing vectors missing at ${outPath}\nRun: npm run pricing:gen`)
    process.exit(1)
  }
  const onDisk = readFileSync(outPath, "utf8")
  if (onDisk !== payload) {
    console.error(
      `PRICING PARITY DRIFT\n` +
        `${outPath}\ndoes not match what src/lib/pricing.ts produces.\n` +
        `Either the TypeScript formula changed (regenerate with npm run pricing:gen,\n` +
        `then update the Java PricingCalculator to match), or the file was hand-edited.`
    )
    process.exit(1)
  }
  console.log(`pricing vectors match src/lib/pricing.ts (${build().cases.length} cases)`)
}
